name: Justfile CI

on:
  pull_request:
    paths:
      - "justfile"
  push:
    branches:
      - main
    paths:
      - "justfile"

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      - name: Run formatter
        run: just --fmt --check
